### PR TITLE
Add support for parent classloading and Jetty JSP example

### PR DESCRIPTION
**Pull request by skjolber**
Some adjustments for JSP-support in Jetty.

### CODE REVIEW

**Comment by mjeanroy** [comment]
Hi @skjolber, 
Thanks for you work, can you just update the Readme to add a note on these new options?
Once done, I'll merge your PR and I'll publish a new release on maven repository ;)

**Comment by skjolber** [comment]
Added a few lines of docs and corresponding code examples. Also added JSP validation to the JSP example.

**Comment by mjeanroy** [comment]
@skjolber Version 0.5.0 has been released and should be available soon on maven repository, thanks!

**Comment by skjolber** [comment]
@mjeanroy Great, thanks!

**Comment by skjolber** [comment]
Just a note, I assumed the maven dependency version was goging to be 0.4.3, so now the docs is incorrect on the main readme.

**Pull request merged**
