### PR TITLE
feat: allow preserving tomcat base directory on server stop

### PR DESCRIPTION
**Pull request by grzegorzt**
Keeping content of the base directory can sometimes be handy,
for example when third party application packaged as war is required
by the server under test. In my case it is gitblit which is unpacked
by maven in generate test resources phase and then gitblit is started
via junit-servers for my application integration tests.
It is much more efficient to preserve tomcat directory between restarts
(even when some small housekeeping is necessary) than copying over
megabytes of jars to temporary directory between gitblit restarts.

### CODE REVIEW

**Comment by mjeanroy** [comment]
@grzegorzt Thanks for your contribution!

I'm ok with your change, but can you just fix the formatting on `EmbeddedTomcatConfiguration.java` file (it seems that you replaced tab indentation with spaces, so the diff is too big to be visible on github)?

Once done, I'll merge that and I'll release a new version ;)

**Comment by grzegorzt** [comment]
Sorry, my bad, I haven't spotted the code uses tabs, I'll fix it.

**Comment by grzegorzt** [comment]
I've fixed formatting as you suggested and updated README.md to indicate there is possibility to disable removing Tomcat base directory.

**Comment by mjeanroy** [comment]
@grzegorzt Awesome, thank you!

**Pull request merged**
